name: 'Setup Bun and dependencies'
description: 'Common setup steps for Bun projects'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: '1.2.17'

    - name: Install dependencies
      run: bun install
      shell: bash 
