name: Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup

      - name: Run all checks
        run: npm run check:all

      - name: Check for changesets
        run: |
          if [ ! -d ".changeset" ] || [ -z "$(find .changeset -name '*.md' -not -name 'README.md' -not -name 'config.json')" ]; then
            echo "⚠️  No changesets found!"
            echo "Run 'npm run release:prepare' and commit the changeset first"
            echo "Then run this workflow again"
            exit 1
          fi
          echo "✅ Changesets found, proceeding with release PR creation"

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' && 
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.head.ref, 'changeset-release/')

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup

      - name: Run all checks
        run: npm run check:all

      - name: Publish to NPM
        uses: changesets/action@v1
        with:
          publish: npm run release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
